### ISSUE TITLE
Command line args

### ISSUE THREAD

**Issue by hernejj** [hernejj/vizigrep#22]
Would there be any benefit to accepting command line args?  We could auto fill in paths and search string if provided and even start the search if we have all the info.

Not sure if there is value in this.

**Comment by markinfo** [comment]
Hi. Vizigrep just now appeared in debian  Stretch. Thank you for developing such usefull tool. 
Could you implement in command line arg "Folder to search"? I would like to add this to the menu of "custom actions" in file manager Thunar. Then Vizigrep can just start searching in the directory which ist actually marked.

**Comment by hernejj** [comment]
I will add this for the next release. Glad you find Vizigrep useful :)

**Comment by hernejj** [comment]
@markinfo 
I just pushed a commit that adds command line support. If you feel like it, test and let me know how it works for you. The argument is documented int the readme and manpage.
